/********************************************************
 * Decompiled by FreeTheTech101 and Edited by SyndiShanX
 * Script: maps\createfx\arcadia_audio.gsc
********************************************************/

#include maps\_anim;

main() {
  // Autogenerated by AnimSounds. Threaded off so that it can be placed before _load( has to create level.scr_notetrack first ).
  thread init_animsounds();
}

init_animsounds() {
  waittillframeend;

}