/********************************************************
 * Decompiled by FreeTheTech101 and Edited by SyndiShanX
 * Script: maps\mp\mp_bog_sh_precache.gsc
********************************************************/

// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main() {
  common_scripts\_destructible_types_anim_airconditioner::main();

  maps\animated_models\foliage_tree_palm_bushy_1::main();
  maps\animated_models\foliage_tree_palm_bushy_2::main();
}