/********************************************************
 * Decompiled by FreeTheTech101 and Edited by SyndiShanX
 * Script: maps\mp\mp_rust_precache.gsc
********************************************************/

// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main() {}