/********************************************************
 * Decompiled by FreeTheTech101 and Edited by SyndiShanX
 * Script: maps\dc_whitehouse_precache.gsc
********************************************************/

// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main() {
  maps\_mig29::main("vehicle_mig29_low");
  common_scripts\_destructible_types_anim_generator::main();
  common_scripts\_destructible_types_anim_light_fluo_on::main();
}