/*********************************************
 * Decompiled and Edited by SyndiShanX
 * Script: maps\mp\mp_rust_long_precache.gsc
*********************************************/

// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main() {
  maps\animated_models\highrise_fencetarp_07b_wind_c::main();
  maps\animated_models\highrise_fencetarp_04b_wind_b::main();
}